bring sysutils as of cut-over date into 2.7 branch

diff --git a/sysutils/xntpd/pkg/INSTALL b/sysutils/xntpd/pkg/INSTALL
--- a/sysutils/xntpd/pkg/INSTALL
+++ b/sysutils/xntpd/pkg/INSTALL
@@ -1,7 +1,14 @@
 #!/bin/sh
-# $OpenBSD: INSTALL,v 1.1 1999/04/08 04:37:27 marc Exp $
+# $OpenBSD: INSTALL,v 1.1.6.1 2000/09/15 05:18:34 marc Exp $
 #
 # Pre/post-installation setup of xntpd
+
+# exit on errors, use a sane path and install prefix
+#
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
+CONFIG_FILE=/etc/ntp.conf
 
 # Function: tell the user what s/he needs to do to use the port just installed
 #
@@ -9,23 +16,17 @@ do_notice()
 {
     echo
     echo "+---------------"
-    echo "| html documentation for $1 can be found in the directory"
-    echo "| ${PREFIX}/share/doc/ntp.  To use this application you must"
+    echo "| HTML documentation for $1 can be found in the directory"
+    echo "| ${PREFIX}/share/doc/ntp.  To use this application you must:"
     echo "|"
-    echo "| 1) create/update the file /etc/ntp.conf (see the documentation)"
+    echo "| 1) create/update the file ${CONFIG_FILE} (see the documentation)"
     echo "| 2) restart your system"
     echo "|"
-    echo "| The system restart is necessary as $1 is started from"
-    echo "| /etc/rc.securelevel before the system securelevel is changed"
+    echo "| The system restart is necessary as tickadj is run from"
+    echo "| /etc/rc.securelevel before the system securelevel is changed."
     echo "+---------------"
     echo
 }
-
-# exit on errors, use a sane path and install prefix
-#
-set -e
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-PREFIX=${PKG_PREFIX:-/usr/local}
 
 # verify proper execution
 #
