bring mail as of cut-over date into 2.7 branch

diff --git a/mail/pine/pkg/INSTALL b/mail/pine/pkg/INSTALL
--- a/mail/pine/pkg/INSTALL
+++ b/mail/pine/pkg/INSTALL
@@ -1,7 +1,13 @@
 #!/bin/sh
-# $OpenBSD: INSTALL,v 1.1 1999/04/08 17:36:49 marc Exp $
+# $OpenBSD: INSTALL,v 1.1.6.1 2000/09/15 05:01:54 marc Exp $
 #
 # Pre/post-installation setup of pine
+
+# exit on errors, use a sane path and install prefix
+#
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
 
 # Function: tell the user what s/he needs to do to use the port just installed
 #
@@ -10,20 +16,13 @@ do_notice()
     echo
     echo "+---------------"
     echo "| Some documentation for $1 can be found in"
-    echo "| ${PREFIX}/share/doc/pine as well as pine(1)."
+    echo "| $PREFIX/share/doc/pine as well as pine(1)."
     echo "|"
     echo "| Please read the documentation for instruction on how to make/update"
     echo "| the configuration files /etc/pine.conf and /etc/pine.conf.fixed"
     echo "+---------------"
     echo
 }
-
-# exit on errors, use a sane path and install prefix
-#
-set -e
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-PREFIX=${PKG_PREFIX:-/usr/local}
-PIDFILE=/var/run/sshd.pid
 
 # verify proper execution
 #
