bring shells as of cut-over date into 2.7 branch

diff --git a/shells/tcsh/pkg/INSTALL b/shells/tcsh/pkg/INSTALL
--- a/shells/tcsh/pkg/INSTALL
+++ b/shells/tcsh/pkg/INSTALL
@@ -1,7 +1,13 @@
 #!/bin/sh
-# $OpenBSD: INSTALL,v 1.1 1999/04/08 15:53:29 marc Exp $
+# $OpenBSD: INSTALL,v 1.1.6.1 2000/09/15 05:16:19 marc Exp $
 #
 # Pre/post-installation setup of tcsh
+
+# exit on errors, use a sane path and install prefix
+#
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
 
 # Function: tell the user what s/he needs to do to use the port just installed
 #
@@ -16,12 +22,6 @@ do_notice()
     echo "+---------------"
     echo
 }
-
-# exit on errors, use a sane path and install prefix
-#
-set -e
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-PREFIX=${PKG_PREFIX:-/usr/local}
 
 # verify proper execution
 #
@@ -50,4 +50,3 @@ case $2 in
 esac
 
 exit 0
-
